8391256: TestZoneTextPrinterParser.java assertion fails with expected: <Mountain Standard Time> but was: <Mountain Daylight Time>
Backport-of: 92fcfff6486d67144c32c67ca4678a7e0b572f4e
(cherry picked from commit 679d0b6ad621a002329474e7eeaefe8bada1ad34)