Fix cacerts count
VerifyCACerts.java is currently failing with:
```
ERROR: 214 entries, should be 221
```

When I updated the count in https://github.com/corretto/corretto-18/commit/f05a9fc051983424667c22239c15198ac0eac654
I was mistakenly checking the count against the certs from the
previous build, so the count is wrong.

JDK certs: 89 (as specified in the test before my update to 221).
Amazon Linux certs before I recently updated them: 132 (+89=221).
Amazon Linux certs after I recently updated them: 125 (+89=214).

89 was always wrong since we add our own certs, 221 would have been
   correct if I hadn't also updated the certs at the same time,
removing 7 AL certs to bring the current correct count to 214.